import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Trug</title>
        <meta
          name="description"
          content="Generated by @surfdb/create-next-surf-app"
        />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <ConnectButton />
        <button
          onClick={async () => {
            const res = await fetch("/api/data", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              credentials: "include",
              body: JSON.stringify({
                data: {
                  title: "test title",
                  content: "test content",
                },
                tags: ["surfdbtest"],
              }),
            });
            console.log({ res });
            const data = await res.json();
            console.log({ data });
          }}
        >
          create data
        </button>
        <button
          onClick={async () => {
            const res = await fetch("/api/data");
            const data = await res.json();
            console.log({ data });
          }}
        >
          get data
        </button>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  );
};

export default Home;
